### ISSUE TITLE
官网相关yoga示例报错

### ISSUE THREAD

**Issue by gdnwr** [antvis/g#973]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://g-next.antv.vision/zh/examples/plugins#yoga-container

### What does the proposed API look like?
错误报告里面选择不了版本号，所以发到功能要求里了，见谅

**Comment by gdnwr** [comment]
@xiaoiver 您好，使用Yoga排版引擎报错，错误与官方示例报错相同，您看什么时候能修复一下

报错如下：
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at YogaPlugin.updateDisplayObjectPosition (YogaPlugin.js:528:1)
    at YogaPlugin.js:163:1
    at Text.Node.forEach (Node.js:346:1)
    at Node.js:348:1
    at Array.forEach (<anonymous>)
    at Rect.Node.forEach (Node.js:347:1)
    at Node.js:348:1
    at Array.forEach (<anonymous>)
    at Rect.Node.forEach (Node.js:347:1)
    at Node.js:348:1

测试版本如下：
"dependencies": {
    "@antv/g": "^5.0.23",
    "@antv/g-canvas": "^1.0.22",
    "@antv/g-plugin-yoga": "^1.0.10",
  }

**Comment by gdnwr** [comment]
@xiaoiver 您好，使用Yoga排版引擎报错，错误与官方示例报错相同，您看什么时候能修复一下

报错如下：
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at YogaPlugin.updateDisplayObjectPosition (YogaPlugin.js:528:1)
    at YogaPlugin.js:163:1
    at Text.Node.forEach (Node.js:346:1)
    at Node.js:348:1
    at Array.forEach (<anonymous>)
    at Rect.Node.forEach (Node.js:347:1)
    at Node.js:348:1
    at Array.forEach (<anonymous>)
    at Rect.Node.forEach (Node.js:347:1)
    at Node.js:348:1

测试版本如下：
"dependencies": {
    "@antv/g": "^5.0.23",
    "@antv/g-canvas": "^1.0.22",
    "@antv/g-plugin-yoga": "^1.0.10",
  }

**Comment by xiaoiver** [comment]
在 `@antv/g@5.1.2` 中已修复。
